### ISSUE TITLE
add routers / static routing (DUE THURSDAY NOV 17)

### ISSUE THREAD

**Issue by programNING** [aekkang/CS143_Network_Simulator#2]
(i think it's due tuesday cause we start student presentations tuesday)

1. **This code in the "receivePacket" event needs to be changed:** (process method in event.py)
`       self.packet.recipient.receive(self.packet, self.start_time);`
so that it supports sending packets through routers, not just through a direct link. This means that the packet.recipient doesn't necessarily receive the packet, but rather the other side of the link. 

To this end I suggest changing the link class so that:

- **(DONE)** it knows what it's attached to (currently we have no data about that)
- **(addressed, see comments)** it has a link.deliverPacket() method that checks what side of the link it is delivering to (i.e. NOT the side the packet is being sent from) and evokes that object's receive method.
- **(DONE)** if the object is a host, its receive method is to send an ACK.
- **(done?)** if the object is a router, its receive method is to process the destination of the packet, calculate where to send it from the routing table, and enqueue another sendPacket() event.

This requires some other shit to be changed:
- **(DONE)** we need to pass extra information about where the packet is being sent from in every sendPacket() event.
- **(addressed, see comments)** this information needs to be passed through all the events (sendpacket, checkbuffer, receivepacket). maybe it can be a field in the packet class that gets changed every sendpacket() evocation.

2. **(DONE)** We need to hardcode the router's routing tables, presumably in the main loop. The alternative is to begin coding dynamic routing, probably.

**Comment by kye308** [comment]
Friends, I have updated the implementation of the link such that it now knows that objects (which I dubbed 'entities') that it is attached to.

I believe that our current implementation of events has not taken the sender of the packet into regard, so we will need to update the event logic accordingly (as Sandra noted). Another field in the packet (i.e. original sender vs sender that (most recently?) sent the packet sounds like a good option? (but we should discuss). Once we do that, we should get test case 0 operational again...and then can proceed on to routers/etc.

**Comment by riichenchen** [comment]
Events have been adjusted to use the ends as of [commit a4e531a4cb3d12862ab225bbc8fb031740fc88c2](https://github.com/aekkang/CS143_Network_Simulator/commit/a4e531a4cb3d12862ab225bbc8fb031740fc88c2).

Addressing the idea of tracking the "recent sender", IMO it doesn't make sense as a field in the Packet class since it's not really native to the packet itself. What I did was to stick a (packet, sender) tuple into the link buffer every time we put something there (i.e. SendPacket events), and unpack the sender when taking a packet off the link. We can discuss if there are any concerns with this implementation.

Router receives still need to be implemented. Right now it just prints "router drops packet"  :laughing:. This does mean we can run test case 1; it's just that the only output you get is all the packets getting dropped.

**Comment by riichenchen** [comment]
Update: added hardcoded routing tables, and receive method for routers. I'm a bit concerned that as per our print statements, we only seem to start receiving data at packet number ~19000? (unclear)

**Comment by riichenchen** [comment]
I think as of [commit d5ef6f4](https://github.com/aekkang/CS143_Network_Simulator/commit/d5ef6f443455223305c9420b1e571cbbe4215148) we've fixed everything here, no? :grinning: 

(if a second person agrees, let's close this issue)

**Comment by programNING** [comment]
i agree!!!

**Comment by kye308** [comment]
Not sure if this is in any way relevant...but (perhaps it's an issue with relevant window size...I decreased it to 10 and this problem disappears.)

Using num_packets = int(ceil(data_amt \* 1.0e4 / packet.DataPkt.PACKET_SIZE))

we get 

(stuff that's fine)
.
.
('PACKET 53', 5836.3399999999965)
('PACKET 54', 5938.739999999996)
('PACKET 55', 6041.139999999996)
('PACKET 56', 6143.539999999995)
('PACKET 57', 6245.939999999995)
('PACKET 58', 6348.339999999995)
('PACKET 59', 6450.739999999994)
('PACKET 60', 6553.139999999994)
('PACKET 61', 6655.539999999994)
('PACKET 62', 6757.939999999993)
('PACKET 63', 6860.339999999993)
('PACKET 100', 6962.7399999999925)
('PACKET 101', 7065.139999999992)
('PACKET 102', 7167.539999999992)
('PACKET 103', 7269.939999999991)
('PACKET 104', 7372.339999999991)
.
.
.
