### ISSUE TITLE
packet order

### ISSUE THREAD

**Issue by riichenchen** [aekkang/CS143_Network_Simulator#5]
Packets can currently be sent out of order if multiple SendPacket events are enqueued at the same start_time.
- Do we care to fix this or is having the packet numbers/ACKs for packet numbers sufficient?
- If we want to fix this, how?
  - Add a delay when enqueuing SendPacket events?
  - Adjust priorities based on packet number?

**Comment by programNING** [comment]
I think the TAs said this could be remedied by adding additional priority on the packet number. However, they also said that this wouldn't matter as much when we implement congestion control. I didn't quite understand... but if it's not a problem it's not a problem.

**Comment by riichenchen** [comment]
Priority for SendPacket events based on packet number has been added, and yeah, it seems like this should not be something we have to worry about. Closing issue.
